export const FETCH_CONGRESS_REQUEST = 'FETCH_CONGRESS_REQUEST';
export const FETCH_CONGRESS_SUCCESS = 'FETCH_CONGRESS_SUCCESS';
export const FETCH_CONGRESS_FAILURE = 'FETCH_CONGRESS_FAILURE';
export const FETCH_IMAGEPROFILE_REQUEST = 'FETCH_IMAGEPROFILE_REQUEST';
export const FETCH_IMAGEPROFILE_SUCCESS = 'FETCH_IMAGEPROFILE_SUCCESS';
